### ISSUE TITLE
Simplify options

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/whatsub#104]
# Task
## Summary
Simplify options

## Project Details
Version: `0.1.3`

## Description
- [x] Get rid of `--src` and `--out` (#106)
- [x] Make subtitle type optional - Use subtitle type detection
  - [x] Use extension (#107)
  - [x] Read the first line to determine as fallback (#108)
